linters:
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - goconst
    - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - mnd
    - perfsprint
    - reassign
    - sqlclosecheck
    - staticcheck
    - unparam
    - unused
    - whitespace
    - usetesting
issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - gosec
        - bodyclose
        - dupl
