version: "2"
formatters:
  enable:
    - gofmt
    - goimports
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - errorlint
    - exhaustive
    - goconst
    - godot
    - godox
    - gosec
    - govet
    - iface
    - importas
    - ineffassign
    - misspell
    - mnd
    - musttag
    - nilerr
    - perfsprint
    - reassign
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testpackage
    - thelper
    - tparallel
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - gosec
          - bodyclose
          - dupl
