version: "2"
formatters:
  enable:
    - gofmt
    - goimports
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - errorlint
    - goconst
    - gocritic
    - godot
    - godox
    - gosec
    - govet
    - iface
    - importas
    - ineffassign
    - intrange
    - misspell
    - mnd
    - musttag
    - modernize
    - nilerr
    - noctx
    - perfsprint
    - reassign
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testpackage
    - thelper
    - tparallel
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
